job_gcc_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages CXXFLAGS="-O3 -flto=auto" LDFLAGS="-flto=auto"
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; (mkdir builds envs; pids=(); for f in `ls *rst`; do python3 /usr/bin/sphinx-build -E -d envs/$f -b doctest . builds/$f $f & pids+=($!); done; for p in "${pids[@]}"; do wait "$p"; done);
  tags:
    - amd64
  except:
    - tags

job_clang_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages CXXFLAGS="-O3" LDFLAGS=""
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; (mkdir builds envs; pids=(); for f in `ls *rst`; do python3 /usr/bin/sphinx-build -E -d envs/$f -b doctest . builds/$f $f & pids+=($!); done; for p in "${pids[@]}"; do wait "$p"; done);
  tags:
    - amd64
  except:
    - tags

job_clang_cxx_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 CXXFLAGS="-stdlib=libc++" LDFLAGS="-lc++abi"
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
  tags:
    - amd64
  except:
    - tags

build_tarball:
  script:
    - ./autogen.sh
    - ./configure
    - make dist-bzip2
    - make dist-xz
    - bunzip2 -k *bz2
    - zstd *.tar
  only:
    - tags
  artifacts:
    paths:
      - graph-tool*bz2
      - graph-tool*xz
      - graph-tool*zst

build_sid:
  script:
    - BASE=debian:sid
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_bullseye:
  script:
    - BASE=debian:bullseye
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_buster:
  script:
    - BASE=debian:buster
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_bionic:
  script:
    - BASE=ubuntu:bionic
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_eoan:
  script:
    - BASE=ubuntu:eoan
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_focal:
  script:
    - BASE=ubuntu:focal
    - img=`echo $BASE | sed s/:/_/`
    - cd release/debian
    - docker build --build-arg BASE=$BASE --build-arg REF=`git log -n1 --pretty='%H'` -t $img .
    - docker run -v $PWD:/mount $img tar -c build | tar x
  only:
    - tags
  artifacts:
    paths:
      - release/debian/build/*

build_docker:
  script:
    - cd release/docker
    - docker build --build-arg REF=`git log -n1 --pretty='%H'` -t tiagopeixoto/graph-tool .
  only:
    - tags
